set dotenv-load
set positional-arguments

# Django commands

serve:
  python3 manage.py runserver

testall:
  python3 manage.py test

@test file:
  python3 manage.py test tests.test_$1

migration:
  python3 manage.py makemigrations

@migrations app:
  python3 manage.py makemigrations $1

migrate:
  python3 manage.py migrate --run-syncdb

admin:
  python3 manage.py createsuperuser

shell:
  python3 manage.py shell --no-startup

poetry_req:
  poetry export --without-hashes --without dev -f requirements.txt -o requirements.txt

@add package:
  poetry add $1 && poetry_req

# django-extensions commands

erd:
  python3 manage.py graph_models -a -g -I DoctorProfile,PatientProfile,Appointment,MedicalRecord,MedicineShop,MedicalTest,Call -o healthlink/erd.png

reset:
  python3 manage.py reset_db --noinput patient 

# MKDocs commands

docs:
  mkdocs serve

# Backend setup

bsetup:
  pip install poetry && cd backend && poetry install && poetry shell && cd ..

# Frontend setup

fsetup:
  cd frontend && nvm use 18 && npm install -g @angular/cli@12.2.0 && npm install && ng serve

# Aggregate commands

run: migrate testall serve

db: migration migrate

rdb: reset db

all: bsetup fsetup run
