set dotenv-load
set positional-arguments

# Django commands

serve:
  poetry run python3 manage.py runserver

ngrok:
  pipx run pyngrok http --domain=monster-open-mistakenly.ngrok-free.app 8000

run: serve ngrok

testall:
  poetry run python3 manage.py test

@test file:
  poetry run python3 manage.py test tests.test_$1

migration:
  poetry run python3 manage.py makemigrations

@migrations app:
  poetry run python3 manage.py makemigrations $1

migrate:
  poetry run python3 manage.py migrate --run-syncdb

admin:
  poetry run python3 manage.py createsuperuser

shell:
  poetry run python3 manage.py shell --no-startup

lock:
  poetry lock && poetry export --without-hashes --without dev -f requirements.txt -o requirements.txt

@add package:
  poetry add $1 && lock

# django-extensions commands

erd:
  poetry run python3 manage.py graph_models -a -g -I DoctorProfile,PatientProfile,Appointment,MedicalRecord,MedicineShop,MedicalTest,Call -o healthlink/erd.png

reset:
  poetry run python3 manage.py reset_db --noinput patient 

# MKDocs commands

docs:
  mkdocs serve

# Backend setup

bsetup:
  pip install poetry && cd backend && poetry install && poetry shell && cd ..

# Frontend setup

fsetup:
  cd frontend && nvm use 18 && npm install -g @angular/cli@12.2.0 && npm install && ng serve

# Aggregate commands

# run: migrate testall serve

db: migration migrate

# rdb: reset db

# all: bsetup fsetup run
