# Generated by Django 5.0.6 on 2024-06-13 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                ("call_id", models.AutoField(primary_key=True, serialize=False)),
                ("peer_id", models.CharField(max_length=100)),
                ("call_date", models.DateTimeField(auto_now_add=True)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.patientprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("chat_id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                ("room_name", models.CharField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.patientprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LLMResponse",
            fields=[
                ("response_id", models.AutoField(primary_key=True, serialize=False)),
                ("transcription", models.TextField()),
                ("response", models.JSONField(blank=True, null=True)),
                ("response_text", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chat.call"
                    ),
                ),
            ],
        ),
    ]
