# Generated by Django 5.0.6 on 2024-06-13 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalTest",
            fields=[
                ("test_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("link", models.URLField()),
                ("lab_name", models.CharField(default="Chughtai Lab", max_length=100)),
                (
                    "image",
                    models.URLField(
                        default="https://pbs.twimg.com/profile_images/1522880282810015745/-Uax8id5_400x400.jpg"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="MedicineShop",
            fields=[
                ("medicine_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("link", models.URLField()),
                ("manufacturer", models.CharField(max_length=100)),
                ("pack_details", models.CharField(max_length=100)),
                ("image", models.URLField()),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("appointment_id", models.AutoField(primary_key=True, serialize=False)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "appointment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("scheduled", "Scheduled"),
                            ("canceled", "Canceled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("paid", "Paid")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.patientprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("doctor_notes", models.TextField(blank=True, null=True)),
                (
                    "past_records",
                    models.FileField(blank=True, null=True, upload_to="past_records/"),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.patientprofile",
                    ),
                ),
            ],
        ),
    ]
