# Generated by Django 5.0.2 on 2024-03-06 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("cardiologist", "Cardiologist"),
                            ("dentist", "Dentist"),
                            ("dermatologist", "Dermatologist"),
                            ("endocrinologist", "Endocrinologist"),
                            ("gastroenterologist", "Gastroenterologist"),
                            ("gynecologist", "Gynecologist"),
                            ("hematologist", "Hematologist"),
                            ("internist", "Internist"),
                            ("nephrologist", "Nephrologist"),
                            ("neurologist", "Neurologist"),
                            ("neurosurgeon", "Neurosurgeon"),
                            ("obstetrician", "Obstetrician"),
                            ("oncologist", "Oncologist"),
                            ("ophthalmologist", "Ophthalmologist"),
                            ("orthopedic surgeon", "Orthopedic Surgeon"),
                            ("otolaryngologist", "Otolaryngologist"),
                            ("pathologist", "Pathologist"),
                            ("pediatrician", "Pediatrician"),
                            ("physiatrist", "Physiatrist"),
                            ("podiatrist", "Podiatrist"),
                            ("psychiatrist", "Psychiatrist"),
                            ("pulmonologist", "Pulmonologist"),
                            ("radiologist", "Radiologist"),
                            ("rheumatologist", "Rheumatologist"),
                            ("surgeon", "Surgeon"),
                            ("urologist", "Urologist"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "qualification",
                    models.CharField(
                        choices=[
                            ("mbbs", "MBBS"),
                            ("bds", "BDS"),
                            ("md", "MD"),
                            ("ms", "MS"),
                            ("dm", "DM"),
                            ("mch", "MCH"),
                            ("phd", "PHD"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("experience_years", models.IntegerField()),
                ("city", models.CharField(max_length=255)),
                ("available_timings", models.TimeField(blank=True, null=True)),
                ("available_days", models.JSONField(blank=True, null=True)),
                ("consultation_fees", models.IntegerField()),
                ("summary", models.TextField()),
                ("wait_time", models.IntegerField(blank=True, null=True)),
                ("recommendation_percent", models.IntegerField(blank=True, null=True)),
                ("patients_count", models.IntegerField(blank=True, null=True)),
                ("reviews_count", models.IntegerField(blank=True, null=True)),
                (
                    "profile_photo_url",
                    models.ImageField(
                        blank=True, null=True, upload_to="doctor_profile_photos/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                ("sex", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "blood_group",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("bmi", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("doctor", "Doctor"), ("patient", "Patient")],
                default="patient",
                max_length=255,
            ),
        ),
    ]
