# Generated by Django 5.0.2 on 2024-03-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_doctorprofile_patientprofile_user_address_user_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("doctor", "Doctor"),
                    ("patient", "Patient"),
                    ("admin", "Admin"),
                ],
                default="patient",
                max_length=255,
            ),
        ),
    ]
