# Generated by Django 5.0.2 on 2024-03-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_user_is_staff_user_is_active_user_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("doctor", "Doctor"),
                    ("patient", "Patient"),
                ],
                max_length=255,
            ),
        ),
    ]
