name: Django Testing

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11.1
      - run: python3 -m pip install --upgrade pip
      - run: python3 --version
      - run: pip --version
      - run: pip install -r backend/requirements.txt
      - run: python3 backend/manage.py test