name: Django Testing

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]
    
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          python3 -m spacy download en_core_web_lg
        working-directory: backend

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .
        working-directory: backend

      - name: Refactor with black
        run: |
          pip install black
          black .
        working-directory: backend

      - name: Run Django tests
        run: python3 manage.py test
        working-directory: backend